Drug/Drug/Controllers/DrugsController.cs
using DrugData;
using DrugData.Models;
using DrugData.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Drug.Controllers
{
    public class DrugsController:Controller
    {
        private readonly ApplicationDbContext _databaseContext;
        private readonly IActionDescriptorCollectionProvider _actionDescriptorCollectionProvider;
        private readonly UserManager<User> _userManager;

        public DrugsController(ApplicationDbContext context,
            IActionDescriptorCollectionProvider actionDescriptorCollectionProvider, UserManager<User> userManager)
        {
            _databaseContext = context;
            _actionDescriptorCollectionProvider = actionDescriptorCollectionProvider;
            _userManager = userManager;
        }
        public ViewResult Show(int id)
        {
            Medication drug = _databaseContext.Drug.Include(t => t.Comments).ThenInclude(p => p.User)
                .Include(p => p.DrugSideEffects).ThenInclude(i => i.SideEffect).Where(p=>p.Quantity>0)
                .Include(r => r.Currency).Include(i => i.Package).ThenInclude(t => t.Measure).Include(p => p.Substitutions)
                .Include(p => p.Manufacturer).Include(e => e.DrugDiseases)
                .ThenInclude(eu => eu.Disease).FirstOrDefault(m => m.DrugId == id);
            return View(drug);
        }

        public async Task<IActionResult> Index(string category, int? page, string[] diseases)
        {
            string _category = category;
            IEnumerable<Medication> drinks;
            ViewData["CurrentCategory"] = category;
            ViewData["Filteri"] = diseases;


            string currentCategory = string.Empty;

            var applicationDbContext = _databaseContext.Drug.OrderBy(p => p.DrugId)
                   .Where(p => p.Quantity > 0)
                .Include(r => r.Currency).Include(i => i.Package).ThenInclude(t => t.Measure)
                .Include(p => p.Manufacturer).Include(e => e.DrugDiseases)
                .ThenInclude(eu => eu.Disease).ToList();

            HashSet<Medication> meds = applicationDbContext.ToHashSet();

            System.Diagnostics.Debug.WriteLine("VELICINA"+diseases.Count());


            if (diseases.Length != 0)
            {
                System.Diagnostics.Debug.WriteLine("USLO");

                HashSet<Medication> ba = new HashSet<Medication>();
                foreach (var i in meds)
                {
                    ba.Add(i);
                }
                foreach (var e in meds)
                {
                    int check = 0;

                    foreach (var p in diseases)
                    {
                        if (e.DrugDiseases.Any(g => g.Disease.DiseaseName.Equals(p)))
                        {
                            check = 1;
                        }
                    }
                    if (check == 0)
                    {
                        ba.Remove(e);
                    }
                }
                System.Diagnostics.Debug.WriteLine("MEDS" + ba.Count);
                meds = ba;
            }

            drinks = meds.ToList();



            if (string.IsNullOrEmpty(category))
            {
                System.Diagnostics.Debug.WriteLine("tu");
                drinks = meds.ToList();

                currentCategory = "Svi proizvodi";
            }
            else
            {
                if (string.Equals("Po cijeni ▼", _category, StringComparison.OrdinalIgnoreCase))
                drinks = meds.ToList().OrderByDescending(p => p.Price);

                else if (string.Equals("Po cijeni ▲", _category, StringComparison.OrdinalIgnoreCase))
                    drinks = meds.ToList().OrderBy(p => p.Price);

                else if (string.Equals("Po isteku valjanosti ▲", _category, StringComparison.OrdinalIgnoreCase))
                    drinks = meds.ToList().OrderBy(p => p.DateExpires);

                else
                {
                    drinks = meds.ToList().OrderByDescending(p => p.DateExpires);

                }

                currentCategory = _category;
            }

            int pageSize = 6;
            ViewBag.Model = applicationDbContext;
            return View(await PaginatedList2<Medication>.CreateAsync(drinks, page ?? 1, pageSize));
        }

      
    }
}

Drug/Drug/Controllers/ManufacturerController.cs
using DrugData;
using DrugData.Models;
using DrugData.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lijek.Controllers
{
    [Authorize(Roles = "Admin")]

    public class ManufacturerController:Controller
    {
        private readonly ApplicationDbContext _databaseContext;
        private readonly IActionDescriptorCollectionProvider _actionDescriptorCollectionProvider;

        public ManufacturerController(ApplicationDbContext context,
            IActionDescriptorCollectionProvider actionDescriptorCollectionProvider)
        {
            _databaseContext = context;
            _actionDescriptorCollectionProvider = actionDescriptorCollectionProvider;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["IdSortParm"] = sortOrder == "Id" ? "Id_desc" : "Id";
            ViewData["CurrentFilter"] = searchString;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            var students = from s in _databaseContext.Manufacturer.Include(p=>p.Drugs)
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.ManufacturerName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.ManufacturerName);
                    break;
                case "Id":
                    students = students.OrderBy(s => s.ManufacturerId);
                    break;
                case "Id_desc":
                    students = students.OrderByDescending(s => s.ManufacturerId);
                    break;
                default:
                    students = students.OrderBy(s => s.ManufacturerName);
                    break;
            }

            int pageSize = 8;
            return View(await PaginatedList<Manufacturer>.CreateAsync(students.AsNoTracking(), page ?? 1, pageSize));
        }

        [HttpGet]
        public ViewResult Add()
        {
            return View(new ManufacturerViewModel());
        }

        [HttpPost]
        public IActionResult Create(ManufacturerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var man = new Manufacturer { ManufacturerName = model.Name,About=model.About,ImagePath=model.ImagePath };
                var x = _databaseContext.Manufacturer.FirstOrDefault(g => g.ManufacturerName == man.ManufacturerName);

                if (x != null)
                {
                    TempData[Constants.Message] = $"Proizvođač tog imena već postoji.\n";
                    TempData[Constants.ErrorOccurred] = true;
                    return View("Add", model);
                }
                _databaseContext.Manufacturer.Add(man);

                TempData["Success"] = true;
                _databaseContext.SaveChanges();
                TempData[Constants.Message] = $"Proizvođač je dodan";
                TempData[Constants.ErrorOccurred] = false;
                return RedirectToAction(nameof(Index));

            }
            return View("Add", model);


        }

        [HttpPost]
        public IActionResult Delete(int id, int? page)
        {
            var man = _databaseContext.Manufacturer
            .FirstOrDefault(p => p.ManufacturerId == id);

            try
            {
                _databaseContext.Manufacturer.Remove(man);
                _databaseContext.SaveChanges();
                TempData[Constants.Message] = $"Proizvođač je obrisan";
                TempData[Constants.ErrorOccurred] = false;
            }
            catch (Exception exc)
            {
                TempData[Constants.Message] = $"Proizvođača nije moguće obrisati jer postoje proizvodi koji ga sadrže.";
                TempData[Constants.ErrorOccurred] = true;
            }
            var x = _databaseContext.Manufacturer.ToList().Count;

            if ((page - 1) * 8 == x && page != 1)
            {
                --page;
            }

            return RedirectToAction(nameof(Index), new { page = page });
        }
        [HttpGet]
        public ViewResult Edit(int id)
        {
            var man = _databaseContext.Manufacturer
            .FirstOrDefault(p => p.ManufacturerId == id);

            ViewData["Success"] = TempData["Success"];

            var model = new EditManufacturerViewModel
            {
                About = man.About,
                ImagePath=man.ImagePath,
                ManufacturerId=man.ManufacturerId,
                ManufacturerName=man.ManufacturerName
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult Update(int id, EditManufacturerViewModel model)
        {
            if (id != 0)
            {
                model.ManufacturerId = id;

            }

            if (ModelState.IsValid)
            {
                var man = _databaseContext.Manufacturer.FirstOrDefault(m => m.ManufacturerId == id);

                man.ManufacturerName = model.ManufacturerName;
                man.About = model.About;
                man.ImagePath = model.ImagePath;

                var x = _databaseContext.Manufacturer.Where(g => (g.ManufacturerName == man.ManufacturerName && g.ManufacturerId!=id)).ToList();
                if (x.Count>0)
                {
                    TempData[Constants.Message] = $"Proizvođač tog imena već postoji.\n";
                    TempData[Constants.ErrorOccurred] = true;
                    return View("Edit", model);
                }

                TempData["Success"] = true;
                _databaseContext.SaveChanges();
                TempData[Constants.Message] = $"Proizvođač je promijenjen";
                TempData[Constants.ErrorOccurred] = false;
                return RedirectToAction(nameof(Index));

            }
            else
            {
                return View("Edit", model);

            }
        }

        public ViewResult Show(int id)
        {
            Manufacturer manufacturer = _databaseContext.Manufacturer.FirstOrDefault(m => m.ManufacturerId == id);
            return View(manufacturer);
        }



    }







}

Drug/Drug/Controllers/ManufacturersController.cs
using DrugData;
using DrugData.Models;
using DrugData.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Drug.Controllers
{
    public class ManufacturersController:Controller
    {

        private readonly ApplicationDbContext _databaseContext;
        private readonly IActionDescriptorCollectionProvider _actionDescriptorCollectionProvider;
        private readonly UserManager<User> _userManager;

        public ManufacturersController(ApplicationDbContext context,
            IActionDescriptorCollectionProvider actionDescriptorCollectionProvider, UserManager<User> userManager)
        {
            _databaseContext = context;
            _actionDescriptorCollectionProvider = actionDescriptorCollectionProvider;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string category, int? page)
        {
            string _category = category;
            ViewData["CurrentCategory"] = category;
            IQueryable<Manufacturer> drinks;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                drinks = from s in _databaseContext.Manufacturer.OrderBy(p => p.ManufacturerId).Include(t=>t.Drugs).Where(t=>t.Drugs.Count>0) select s;
                currentCategory = "Svi proizvođači";
            }
            else
            {
                if (string.Equals("Po broju proizvoda ▼", _category, StringComparison.OrdinalIgnoreCase))
                    drinks = from s in _databaseContext.Manufacturer.Include(t => t.Drugs).Where(t => t.Drugs.Count > 0).OrderByDescending(p => p.Drugs.Count) select s;
                else
                    drinks = from s in _databaseContext.Manufacturer.Include(t => t.Drugs).Where(t => t.Drugs.Count > 0).OrderBy(p => p.Drugs.Count) select s;

                currentCategory = _category;
            }

            int pageSize = 3;
            return View(await PaginatedList<Manufacturer>.CreateAsync(drinks.AsNoTracking(), page ?? 1, pageSize));

        }

    }
}

Drug/Drug/Views/Manufacturer/Add.cshtml
@model DrugData.Models.ViewModels.ManufacturerViewModel

<form asp-action="Create" method="POST">
    <div asp-validation-summary="All" class="text-danger"></div>
    <h2>
        Novi proizvođač
    </h2>
    <div class="form-group">
        <label asp-for="Name">Naziv </label>
        <input asp-for="Name" id="da" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="About">O proizvođaču </label>
        <textarea asp-for="About" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="ImagePath">Poveznica na sliku </label>
        <input asp-for="ImagePath" id="da" class="form-control" />
    </div>

    <div class="text-center">
        <button type="submit" class="btn btn-primary">Spremi</button>
        <a asp-action="Index">
            <button type="button" class="btn btn-secondary">Odustani</button>
        </a>
    </div>
</form>

<style>
    #da {
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }
</style>

Drug/Drug/Views/Manufacturer/Edit.cshtml
@model DrugData.Models.ViewModels.EditManufacturerViewModel

<form asp-action="Update" asp-route-id="@Model.ManufacturerId" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <h2>Uredi</h2>
    <div class="form-group">
        <label asp-for="ManufacturerName">Naziv </label>
        <input asp-for="ManufacturerName" id="da" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="About">O proizvođaču </label>
        <textarea asp-for="About" id="da" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="ImagePath">Poveznica na sliku </label>
        <input asp-for="ImagePath" id="da" class="form-control" />
    </div>

    <div class="text-center">
        <button type="submit" class="btn btn-primary">Spremi</button>
        <a asp-action="Index">
            <button type="button" class="btn btn-secondary">Odustani</button>
        </a>
    </div>

</form>

<style>
    #da {
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }
</style>

Drug/Drug/Views/Manufacturer/Index.cshtml
@model PaginatedList<DrugData.Models.Manufacturer>

<h2>Proizvođači</h2>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Pretraži: <input type="text" id="da" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Pretraži" class="btn btn-default" /> |
            <a asp-action="Index">Cijeli popis</a>
        </p>
    </div>
</form>
<table class="table table-striped table-bordered table-sm">
    <tr>
        <th class="text-center">
            <a asp-action="Index" asp-route-sortOrder="@ViewData["IdSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">ID</a>
        </th>
        <th class="text-center"><a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Naziv</a></th>
        <th class="text-center">
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr data-toggle="collapse" id="xman" data-target="@("#" + item.ManufacturerId.ToString())" style="cursor:pointer;">
            <td class="text-center">@item.ManufacturerId</td>
            <td class="text-center">@item.ManufacturerName</td>
            <td class="text-center">
                <a asp-action="Edit" asp-route-id="@item.ManufacturerId" class="btn btn-warning btn-sm">✎</a>
                <form asp-action="Delete" asp-route-id="@item.ManufacturerId" asp-route-page="@(Model.PageIndex)"
                      method="POST" style="display: inline-block">
                    <button type="submit" class="btn btn-danger btn-sm">✘</button>
                </form>
            </td>
        <tr></tr>
        <tr class="bg-light">
            <td colspan="8" style="padding:0;margin:0;">
                <div id="@item.ManufacturerId" class="subRow collapse">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="column1">
                                <img src=@item.ImagePath class="imageCell" height="190" width="160" />
                            </div>
                            <div class="column">
                                <div>
                                    <h4><b><center>@item.ManufacturerName</center></b></h4>
                                </div>
                                <div>
                                    @item.About
                                </div>
                            </div>
                            <div class="column1">
                                <div>
                                    <h4><b><center>Proizvodi</center></b></h4>
                                </div>
                                <div>
                                    @if (item.Drugs.Count == 0)
                                    {
                                        <center>Trenutno nema proizvoda</center>

                                    }
                                    else
                                    {
                                        @foreach (var x in item.Drugs)
                                        {
                                            <center>
                                                <a asp-controller="Drugs" asp-action="Show" asp-route-id="@x.DrugId">@x.DrugName</a>
                                            </center>

                                        }
                                    }
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </td>
        </tr>

        </tr>

    }


</table>

<div class="text-center">
    <a asp-action="Add" class="btn btn-primary">Novi proizvođač</a>
</div>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    ◄

</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    ►
</a>


<style>
    #xman {
        background-color: white;
        color: black;
        cursor: pointer;
        padding: 30px;
        width: 100%;
        border: none;
        text-align: left;
        outline: none;
        font-size: 15px;
    }

        .active, #xman:hover {
            background-color: #c5c5c5;
        }

    #cman {
        padding: 0 14px;
        display: none;
        overflow: hidden;
        background-color: #ff0000;
    }
    #da {
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }
</style>

<style>
    * {
        box-sizing: border-box;
    }

    /* Create two equal columns that floats next to each other */
    .column {
        float: left;
        width: 35%;
        padding: 10px;
        height: 240px; /* Should be removed. Only for demonstration */
    }

    .column1 {
        float: left;
        width: 20%;
        padding: 10px;
        height: 240px; /* Should be removed. Only for demonstration */
    }

    /* Clear floats after the columns */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }
</style>