Drug/Drug/Controllers/CartController.cs
using DrugData;
using DrugData.Models;
using DrugData.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lijek.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Cart _cart;
        public CartController(Cart cart, ApplicationDbContext context)
        {
            _cart = cart;
            _context = context;
        }

        public ViewResult Index()
        {
            System.Diagnostics.Debug.WriteLine("INDEXXX");

            var items = _cart.GetCartDrugs();
            System.Diagnostics.Debug.WriteLine("broj" + items.Count);
            _cart.DrugCarts = items;

            var cVM = new CartViewModel
            {
                Cart = _cart,
                CartTotal = _cart.getCartTotal()

            };
            return View(cVM);
        }
        public RedirectToActionResult AddToCart(int drugId)
        {

            var selected = _context.Drug.FirstOrDefault(p => p.DrugId == drugId);

            if (selected != null)
            {
                
                _cart.AddToCart(selected, 1);
            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult RemoveFromCart(int drugId)
        {
            var selected = _context.Drug.FirstOrDefault(p => p.DrugId == drugId);
            if (selected != null)
            {
                _cart.RemoveFromCart(selected);
            }
            return RedirectToAction("Index");
        }
    }

}

Drug/Drug/Controllers/DrugController.cs
using DrugData;
using DrugData.Models;
using DrugData.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Drug.Controllers
{

    public class DrugController:Controller
    {
        private readonly ApplicationDbContext _databaseContext;
        private readonly IActionDescriptorCollectionProvider _actionDescriptorCollectionProvider;
        private readonly UserManager<User> _userManager;

        public DrugController(ApplicationDbContext context,
            IActionDescriptorCollectionProvider actionDescriptorCollectionProvider, UserManager<User> userManager)
        {
            _databaseContext = context;
            _actionDescriptorCollectionProvider = actionDescriptorCollectionProvider;
            _userManager = userManager;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["IdSortParm"] = sortOrder == "Id" ? "Id_desc" : "Id";
            ViewData["CurrentFilter"] = searchString;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            var students = from s in _databaseContext.Drug.Include(p => p.Manufacturer)
                .Include(p => p.DrugSideEffects).ThenInclude(i => i.SideEffect)
                .Include(r => r.Currency).Include(i => i.Package).ThenInclude(t=>t.Measure).Include(p => p.Substitutions)
                .Include(e => e.DrugDiseases).ThenInclude(eu => eu.Disease)
                
            select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.DrugName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.DrugName);
                    break;
                case "Id":
                    students = students.OrderBy(s => s.DrugId);
                    break;
                case "Id_desc":
                    students = students.OrderByDescending(s => s.DrugId);
                    break;
                default:
                    students = students.OrderBy(s => s.DrugName);
                    break;
            }

            int pageSize = 8;
            return View(await PaginatedList<Medication>.CreateAsync(students.AsNoTracking(), page ?? 1, pageSize));
        }
        public ViewResult Show(int id)
        {
            Medication drug = _databaseContext.Drug.Include(t=>t.Comments).ThenInclude(p=>p.User)
                .Include(p => p.DrugSideEffects).ThenInclude(i => i.SideEffect)
                .Include(r => r.Currency).Include(i => i.Package).ThenInclude(t => t.Measure).Include(p => p.Substitutions)
                .Include(p => p.Manufacturer).Include(e => e.DrugDiseases)
                .ThenInclude(eu => eu.Disease).FirstOrDefault(m => m.DrugId == id);
            return View(drug);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Add()
        {
            ViewData["Categories"] = _databaseContext.Disease.ToList();
            ViewData["SideEffects"] = _databaseContext.SideEffect.ToList();
            ViewData["Manufacturers"] = _databaseContext.Manufacturer.ToList();
            ViewData["Drugs"] = _databaseContext.Drug.ToList();
            ViewData["Packages"] = _databaseContext.Package.Include(t => t.Measure).ToList();
            ViewData["Currencies"] = _databaseContext.Currency.ToList();
            ViewData["Measures"] = _databaseContext.Measure.ToList();


            return View(new DrugViewModel());
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DrugViewModel model)
        {
            ViewData["Categories"] = _databaseContext.Disease.ToList();
            ViewData["Manufacturers"] = _databaseContext.Manufacturer.ToList();
            ViewData["SideEffects"] = _databaseContext.SideEffect.ToList();
            ViewData["Drugs"] = _databaseContext.Drug.ToList();
            ViewData["Packages"] = _databaseContext.Package.Include(t=>t.Measure).ToList();
            ViewData["Currencies"] = _databaseContext.Currency.ToList();
            ViewData["Measures"] = _databaseContext.Measure.ToList();



            if (ModelState.IsValid)
            {
                Manufacturer man;
                Manufacturer x;

                if (model.ManufacturerType == "new")
                {
                  
                    if (model.Manufacturer.ManufacturerName==null || model.Manufacturer.About == null|| model.Manufacturer.ImagePath == null)
                    {
                        TempData[Constants.Message] = $"Sva polja za proizvođača su obavezna.\n";
                        TempData[Constants.ErrorOccurred] = true;
                        System.Diagnostics.Debug.WriteLine("fuego");
                        return View("Add", model);
                    }

                    man = model.Manufacturer;
                    x = _databaseContext.Manufacturer.FirstOrDefault(g => g.ManufacturerName == man.ManufacturerName);

                    if (x != null)
                    {
                        TempData[Constants.Message] = $"Proizvođač tog imena već postoji.\n";
                        TempData[Constants.ErrorOccurred] = true;
                        return View("Add", model);
                    }
                    _databaseContext.Manufacturer.Add(man);
                }
                else
                {
                    man = _databaseContext.Manufacturer.Find(model.ManufacturerId);
                }

                ///////////////
                Package pac;
                Package y;

                if (model.PackageType == "new")
                {
                    if (model.Package.PackageType == null || model.Package.Quantity ==0 || model.Package.IndividualSize==0 )
                    {
                        TempData[Constants.Message] = $"Sva polja za pakiranje su obavezna te moraju biti različita od 0.\n";
                        TempData[Constants.ErrorOccurred] = true;
                        System.Diagnostics.Debug.WriteLine("fuego");
                        return View("Add", model);
                    }

                    var m = _databaseContext.Measure.FirstOrDefault(t => t.MeasureId == model.MeasureId);
                    pac = model.Package;
                    pac.Measure = m;
                    pac.MeasureName = m.MeasureName;

                    y = _databaseContext.Package.FirstOrDefault(g => (g.PackageType == pac.PackageType && g.IndividualSize == pac.IndividualSize && g.Quantity == pac.Quantity && g.Measure == pac.Measure));

                    if (y != null)
                    {
                        TempData[Constants.Message] = $"Takvo pakiranje već postoji.\n";
                        TempData[Constants.ErrorOccurred] = true;
                        return View("Add", model);
                    }
                    _databaseContext.Package.Add(pac);
                }
                else
                {
                    pac = _databaseContext.Package.Include(t=>t.Measure).FirstOrDefault(t=>t.PackageId==model.PackageId);
                }
                ///////////////

                try
                {
                    if (model.SubstitutionType == "existing" && !model.DrugIds.Any())
                    {

                    }

                }
                catch (Exception exc)
                {
                    System.Diagnostics.Debug.WriteLine("konj");
                    TempData[Constants.Message] = $"Zamjenski proizvodi su obavezni.\n";
                    TempData[Constants.ErrorOccurred] = true;
                    return View("Add", model);
                }

                var val = _databaseContext.Currency.FirstOrDefault(m => m.CurrencyId == model.CurrencyId);
                //var pac = _databaseContext.Package.FirstOrDefault(m => m.PackageId == model.PackageId);
                var drugCategories = new List<DrugDisease>();
                var ses = new List<DrugSideEffect>();

                var drug = new Medication
                {

                    DrugName = model.Name,
                    DateProduced = model.Produced,
                    DateExpires = model.Expires,
                    Price = model.Price,
                    Quantity = model.Stock,
                    Manufacturer = man,
                    Package = pac,
                    Currency = val,
                    Usage = model.Usage,
                    ImagePath=model.ImagePath
                 

                };
                

                if (model.SubstitutionType == "existing")
                {
                    var drugs = new List<Medication>();
                    drugs = model.DrugIds.Select(id => _databaseContext.Drug.Find(id)).ToList();
                    drug.Substitutions = drugs;

                }

                drugCategories = model.CategoryIds.Select(id => _databaseContext.Disease.Find(id))
               .Select(u => new DrugDisease { Disease = u, Drug = drug }).ToList();

                    ses = model.SideEffectIds.Select(id => _databaseContext.SideEffect.Find(id))
                   .Select(u => new DrugSideEffect { SideEffect = u, Drug = drug }).ToList();

Drug/Drug/Controllers/SearchController.cs
using DrugData;
using DrugData.Models;
using DrugData.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;

namespace Lijek.Controllers
{
    public class SearchController:Controller
    {
        private readonly ApplicationDbContext _databaseContext;
        private readonly IActionDescriptorCollectionProvider _actionDescriptorCollectionProvider;


        public SearchController(ApplicationDbContext context,
            IActionDescriptorCollectionProvider actionDescriptorCollectionProvider)
        {
            _databaseContext = context;
            _actionDescriptorCollectionProvider = actionDescriptorCollectionProvider;
        }

        public ViewResult SearchAction(string searchString)
        {
            if (string.IsNullOrEmpty(searchString)) {
                return View();
            }

            var searchLower = searchString.ToLower().Split(" ");
            var  drugs =
                _databaseContext.Drug.Include(i => i.Package).ThenInclude(t => t.Measure).Where(c => searchForArray(c.DrugName.ToLower(), searchLower)).ToList();


            var searchResults = new SearchActionViewModel
            {
                Drugs=drugs
            };
            return View(searchResults);
        }

        private bool searchForArray(string value, string[] searchStrings)
        {
            foreach (var s in searchStrings)
            {
                if (value.Contains(s)) return true;
            }
            return false;
        }


    }
}

Drug/Drug/Views/Shared/DrugSummary.cshtml
@model Medication

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail"  >
        <img src=@Model.ImagePath id="lol" />
        <div class="caption">
            @if (User.IsInRole("Admin"))
            {
                if (Model.Quantity < 5 || Model.DateExpires <= DateTime.Now)
                {
                    <h3 class="pull-right">
                        <a asp-controller="Drug" asp-action="Edit"
                           asp-route-id="@Model.DrugId"><img class="pull-right" src="~/images/warning.png" alt="" width="35" height="35" /></a>
                    </h3>

                }

            }
            else if (User.IsInRole("User"))
            {
                    <div>
                        <h3 class="pull-right">
                            <a asp-controller="Cart" asp-action="AddToCart"
                               asp-route-drugId="@Model.DrugId"><img class="pull-right" src="~/images/cart.png" alt="" width="35" height="35" /></a>
                        </h3>
                    </div>
                

            }
            else if (!User.Identity.IsAuthenticated)
            {
                <h3 class="pull-right">
                    <a asp-controller="Account" asp-action="Login"
                       ><img class="pull-right" src="~/images/cart.png" alt="" width="35" height="35" /></a>
                </h3>
            }
                <h4 id="max">
                    <a asp-controller="Drugs" asp-action="Show" asp-route-id="@Model.DrugId">@Model.DrugName @Model.Package.IndividualSize@Model.Package.Measure.MeasureName</a>
                    @if (Model.Currency.CurrencyName == "HRK")
                    {
                    <h4><b>@Model.Price.ToString() kn</b></h4>

                                    }
                    else
                    {
                        <b>@Model.Price.ToString()@Model.Currency.CurrencyName.ToString()</b>



                    }
                </h4>
        </div>
    </div>
</div>

<style>
    #lol{
        height:200px
    }
    #max {
        font-size: 25px;
    }
</style>

Drug/Drug/Views/Shared/Search.cshtml
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="search-container">
    <form asp-controller="Search" asp-action="SearchAction" method="get">
        <input type="text" placeholder="Pretraži.." name="SearchString">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

<style>
    .search-container {
        float: right;
        margin-left: 25px;
    }

    input[type=text] {
        padding: 6px;
        margin-top: 8px;
        font-size: 17px;
        border: none;
    }

    .search-container button {
        float: right;
        padding: 6px 10px;
        margin-top: 8px;
        margin-right: 16px;
        background: #ddd;
        font-size: 17px;
        border: none;
        cursor: pointer;
    }

        .search-container button:hover {
            background: #ccc;
        }

    media screen and (max-width: 600px) {
        .search-container

    {
        float: none;
    }

    input[type=text], .search-container button {
        float: none;
        display: block;
        text-align: left;
        width: 100%;
        margin: 0;
        padding: 14px;
    }

    input[type=text] {
        border: 1px solid #ccc;
    }
    }
</style>

Drug/Drug/Views/Shared/_Docs.cshtml
<meta charset="utf-8" />

<ul class="nav navbar-nav navbar">
    <li class="nav-item"><a asp-controller="Doctor" asp-action="List" class="nav-link">Djelatnici</a></li>
</ul>

Drug/Drug/Views/Shared/_Drugs.cshtml
<meta charset="utf-8" />

<ul class="nav navbar-nav navbar">
    <li class="nav-item"><a class="navbar-brand" asp-controller="Drugs" asp-action="Index">
    <text id="max">
        <img src="~/images/cross.png" alt="" width="35" height="35" /> Sanitas
    </text>
</a></li>
</ul>

Drug/Drug/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <!--<meta name="viewport" content="width=device-width, initial-scale=1.0" />-->
    <!--<link href="~/Search.css" rel="stylesheet" />-->
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <title>Ljekarna Sanitas</title>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" id="robo" role="navigation">
        <div class="container" >
            <div class="navbar-header"  >
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" asp-controller="Drugs" asp-action="Index"><text id="max"><img src="~/images/cross.png" alt="" width="25" height="25" /> Sanitas</text></a>
            </div>

            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    @await Component.InvokeAsync("CategoryMenu")
                    @await Component.InvokeAsync("ManufacturerMenu")
                    @await Html.PartialAsync("_Docs")
                    @await Html.PartialAsync("Search")



                </ul>
                @await Html.PartialAsync("_LoginPartial")
                @await Component.InvokeAsync("CartSummary")


            </div>

            <style>
                body {
                    margin: 0;
                    font-family: Arial, Helvetica, sans-serif;
                }

                .navbar {
                    overflow: hidden;
                    background-color: #333;
                    font-family: Arial;
                }
                    .navbar a {
                        float: left;
                        font-size: 16px;
                        color: white;
                        text-align: center;
                        padding: 14px 16px;
                        text-decoration: none;
                    }

                #robo {
                    overflow: hidden;
                    background-color: #333;
                    z-index:5;
                }

                    #robo a {
                        float: left;
                        color: #f2f2f2;
                        text-align: center;
                        padding: 14px 16px;
                        text-decoration: none;
                        font-size: 17px;
                    }

                        #robo a:hover {
                            background-color: #ddd;
                            color: black;
                        }

                        #robo a.active {
                            background-color: #4CAF50;
                            color: white;
                        }
                #max {
                    font-size: 20px;
                }

            </style>

            <div class="navbar-collapse collapse">

                </ul>


            </div>
            <!--<div class="navbar-collapse collapse">

    </div>-->
        </div>
    </nav>
    <div class="container body-content">
        <div>
            <div id="tempmessage" class="alert"></div>
            @if (TempData[Constants.Message] != null)
            {
                bool error = false;
                var obj = TempData[Constants.ErrorOccurred];
                if (obj != null)
                {
                    error = (bool)obj;
                }
                <div class="alert @(error ? "alert-danger" : "alert-success")">@TempData[Constants.Message]</div>
            }
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Sanitas</p>
        </footer>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>